///
/// @Generated by Mockolo
///

import CoreSpotlight
import Foundation
import MDBConstants
import MDBDataLayer
import MDBNetworking
@testable import MDBServices
import MDBUtilities
import MobileCoreServices
import UIKit

public class NetworkingProviderProtocolMock: NetworkingProviderProtocol {
  public init() {}
  public init(networkingService: NetworkingServiceProtocol) {
    _networkingService = networkingService
  }

  public private(set) var networkingServiceSetCallCount = 0
  private var _networkingService: NetworkingServiceProtocol! { didSet { networkingServiceSetCallCount += 1 } }
  public var networkingService: NetworkingServiceProtocol {
    get { _networkingService }
    set { _networkingService = newValue }
  }
}
